apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mssql-depl
      labels:
        app: mssql-depl
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mssql
      template:
        metadata:
          name: mssql
          labels:
            app: mssql
        spec:
          containers:
            - name: mssql
              image: mcr.microsoft.com/mssql/rhel/server:2019-latest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 1433
                  protocol: TCP
              env:
                - name: MSSQL_PID
                  value: "Express"
                - name: ACCEPT_EULA
                  value: "Y"
                - name: mssql
                  valueFrom:
                    secretKeyRef:
                      key: SA_PASSWORD
              volumeMounts:
                - mountPath: /var/opt/mssql/data
                  name: mssqldb
          volumes:
            - name: mssqldb
              persistentVolumeClaim:
                claimName: mssql-claim
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      name: mssql-clusterip-srv
    spec:
      type: ClusterIP
      selector:
        app: mssql
      ports:
        - port: 1433
          name: mssql
          protocol: TCP
          targetPort: 1433
  - apiVersion: v1
    kind: Service
    metadata:
      name: mssql-loadbalancer
    spec:
      type: LoadBalancer
      selector:
        app: mssql
      ports:
        - port: 1433
          protocol: TCP
          targetPort: 1433